name: dan211
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  dio: 4.0.4
  cookie_jar: 3.0.1
  path_provider: 2.0.9
  dio_cookie_manager: 2.0.0
  html: 0.15.0
  url_launcher: 6.0.20
  flutter_html: ^2.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

