name: dan211
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: 2.10.5

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  dio: 4.0.4
  cookie_jar: 3.0.1
  path_provider: 2.0.9
  dio_cookie_manager: 2.0.0
  html: 0.15.0
  url_launcher: 6.0.20
  flutter_html: ^2.2.1
  modal_bottom_sheet: ^2.0.1
  get_storage: 2.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

  # flutter_launcher_name:
  #   git:
  #     url: https://github.com/d1y/flutter_launcher_name

  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.2
  # icons_launcher: ^1.1.7

flutter: 
  uses-material-design: true

  assets:
    - assets/buitln/
    - assets/empty.png

# flutter pub run flutter_launcher_name:main
flutter_launcher_name:
  name: "211工程"

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  macos: true
  image_path: "design/dan211.png"
  image_path_macos: "design/dan211_round.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: design/dan211.png
  color: "#FF7CC1"
  ios: true
  android: true